title: John Doe # your name (or website title) here
logo: "/images/foto_adeline.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Adeline is currently a final year undergraduate student pursuing a degree in Mathematics, UIN Syarif Hidayatullah Jakarta. 
  She is interested in analytics, build statistical models, data visualization, machine learning, and data science. 
  Other than her study, Adeline is non-academically active. She joined several organizations, volunteers, and other social events.
  <br><br><br>
  <a href="https://www.linkedin.com/in/adelinehikmalia/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
